# Generated by Django 5.0.4 on 2025-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
    ]
