# Generated by Django 5.2 on 2025-05-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_menu_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
